/*
 * Exercise 15.29: Repeat your program, but this time store shared_ptrs to
 * objects of type Quote. Explain any discrepancy in the sum generated by the
 * this version and the previous program. If there is no discrepancy, explain
 * why there isn’t one.
 */

int main() { return 0; }

/*
 * $ g++ -o main chapter-15/exercise-29.cc && ./main

 */
